modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-badlandsbiomesdimension"
license = "ARR"

[[mods]]
modId = "badlandsbiomesdimension"
version = "${version}"
displayName = "Badlands Biomes Dimension"
authors = "mahmudindev"
description = '''
Add badlands biomes as separate dimension.
'''
logoFile = "assets/badlandsbiomesdimension/icon.png"

[[dependencies.badlandsbiomesdimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.badlandsbiomesdimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.badlandsbiomesdimension]]
modId = "modifiedbiomesource"
type = "required"
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.badlandsbiomesdimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.badlandsbiomesdimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "badlandsbiomesdimension.mixins.json"
